# Generated by Django 4.2.10 on 2024-02-16 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documentsInfo/')),
                ('datePublished', models.DateField(default=datetime.date.today, verbose_name='дата публикации документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Название информативного изобрежения')),
                ('image', models.ImageField(upload_to='imagesInfo/', verbose_name='Информативное изображение')),
                ('datePublished', models.DateField(default=datetime.date.today, verbose_name='дата публикации информативного изображения')),
            ],
            options={
                'verbose_name': 'Информативное изображение',
                'verbose_name_plural': 'Информативные изображения',
            },
        ),
        migrations.CreateModel(
            name='VideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Название видеоролика')),
                ('file', models.FileField(upload_to='videoInfo/')),
                ('datePublished', models.DateField(default=datetime.date.today, verbose_name='дата публикации видеоролика')),
            ],
            options={
                'verbose_name': 'Видеоролик',
                'verbose_name_plural': 'ВИдеоролиики',
            },
        ),
    ]
