# Generated by Django 4.2.10 on 2024-02-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteOSH', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageinfo',
            old_name='image',
            new_name='file',
        ),
    ]
