version: '3.7'

services:
  backend:
    build: './backend'
    restart: always
    volumes:
      - './backend/project/:/home/app/'
    ports:
      - '8001:8001'


  nginx:
    build: './nginx'
    restart: always
    ports:
      - '80:80'

    volumes:
      - ./backend/:/home/app/backend
      - ./frontend/public:/home/app/frontend/public/
      - ./frontend/fonts/:/home/app/frontend/fonts/
      - ./frontend/images/:/home/app/frontend/images/
      - ./frontend/index.html:/home/app/frontend/index.html

    depends_on:
      - backend